https://mifosforge.jira.com/browse/G2PCCODV-223
openMF/ph-ee-dpg-exporter pull request #2
Opened 2023-10-20 11:31 UTC by Anover000

https://mifosforge.jira.com/browse/G2PCCODV-223

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Acknowledge that we will not merge PRs that are not passing the checks ("green") - it is your (author's) responsibility to get a proposed PR to pass all the checks, not primarily the project's maintainers.

- [x] The PR title should include a JIRA ticket

- [ ] Design-related bullet points or design document links related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or API documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

- [ ] Followed coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

FYI our guidelines for code reviews same as https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-10-20 12:18 UTC, fynmanoj requested changes

2023-10-20 12:18 UTC, fynmanoj commented on build.gradle
> +            //			artifact file("build/libs/ph-ee-dpg-exporter-0.0.1-SNAPSHOT.jar")
is this block required? if so remove the commented lines

2023-10-20 12:18 UTC, fynmanoj commented on build.gradle
> +            // username = 'avik@fynarfin.io'    publisher user name
remove credentials from here. credentials should be applied from pipeline

2023-10-20 12:18 UTC, fynmanoj commented on settings.gradle
> +    app_username = "avik@fynarfin.io"
remove plain text credentials

2023-10-20 12:18 UTC, fynmanoj commented on src/main/java/com/netflix/conductor/pheedpgexporter/listeners/CustomTaskStatusListener.java
> + * Copyright 2023 Netflix, Inc.
we don't need to add this license here. please run a gradle rat check.  Our licenses are different

2023-10-20 12:18 UTC, fynmanoj commented on src/main/java/com/netflix/conductor/pheedpgexporter/listeners/CustomTaskStatusListener.java
are these files copied from Netflix conductor? 
We shouldn't keep the package structure are Netflix alone. the structure should include org.mifos and Netflix can be added under that if at all required.

2023-10-20 12:18 UTC, fynmanoj commented on src/main/resources/application.yaml
> +    bootstrap-servers: localhost:9092
localhost may not be appropriate when this this running from cluster.
make sure you keep product-level defaults here.

2023-10-25 13:18 UTC, Anover000 commented on settings.gradle
> +    app_username = "avik@fynarfin.io"
removed

2023-10-25 13:20 UTC, Anover000 commented on src/main/java/com/netflix/conductor/pheedpgexporter/listeners/CustomTaskStatusListener.java
the package structure is as such because exporter has to go as a dependent module to Netflix Conductor. Since Netflix Conductor has Component Scan enable for selective packages, its necessary to have their package structure.

2023-10-25 13:21 UTC, Anover000 commented on src/main/resources/application.yaml
> +    bootstrap-servers: localhost:9092
It is anyways going to be overridden from helm

2023-10-25 13:23 UTC, Anover000 commented on src/main/java/com/netflix/conductor/pheedpgexporter/listeners/CustomTaskStatusListener.java
> + * Copyright 2023 Netflix, Inc.
removed the Netflix license

2023-10-25 13:24 UTC, Anover000 commented on build.gradle
> +            // username = 'avik@fynarfin.io'    publisher user name
removed

2023-10-27 12:59 UTC, fynmanoj approved these changes

2023-10-27 12:59 UTC, merged